task: GTSRB
synthesizer: Pattern


batch_size: 64
test_batch_size: 100
#lr: 0.001
lr: 0.0008
#momentum: 0.9
momentum: 0
#decay: 0.0005
decay: 0
#epochs: 350
epochs: 140
save_on_epochs: []
#optimizer: SGD
optimizer: Adam
log_interval: 100
scheduler: False

#loss_low: 0.96

poisoning_proportion: 1.0
backdoor_label: 8
backdoor: True
#backdoor_dynamic_position: True
backdoor_dynamic_position: False

loss_balance: MGDA
mgda_normalize: loss

save_model: True
log: True
tb: True

transform_train: True

resume_model: premodel/GTSRB_model_last.pt.tar

loss_tasks:
  - normal
  - backdoor
#  - neural_cleanse
#  - sentinet_evasion



#poison_images_test:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588
#
#poison_images:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588